-- ============================================================
-- 031 — Optimistic concurrency, everywhere
-- ============================================================
-- Migration 030 put a `version` counter + the `bump_version` BEFORE UPDATE
-- trigger on the four document-shaped tables. This extends the SAME mechanism to
-- every remaining table that has a user-facing UPDATE path, so state management
-- is uniform across the whole app: no editable row anywhere is last-write-wins.
--
-- The trigger is already generic (030's DO-loop attaches bump_version to ANY
-- public BASE TABLE that has a `version` column and lacks the trigger), so all
-- this migration does is add the column to the remaining tables and re-run that
-- loop. See docs/DATABASE_ARCHITECTURE.md §11 and src/lib/concurrency.js.
--
-- Deploy order: SHIP THE APP CODE FIRST (same story as 030). Until this runs,
-- GETs simply don't carry a `version` for these tables, clients send no base
-- version, and versionedWrite falls back to the historical unguarded write —
-- behaviour identical to today. No data backfill beyond the column default.
--
-- Idempotent: column adds are IF NOT EXISTS; the trigger loop is the same
-- idempotent block as 030.
-- ============================================================

-- Tables with a user-facing edit (UPDATE) path. Each is read into the client,
-- edited, and written back, so each can lose an update without a guard.
ALTER TABLE public.holdings             ADD COLUMN IF NOT EXISTS version integer NOT NULL DEFAULT 1;
ALTER TABLE public.research_links       ADD COLUMN IF NOT EXISTS version integer NOT NULL DEFAULT 1;
ALTER TABLE public.documents            ADD COLUMN IF NOT EXISTS version integer NOT NULL DEFAULT 1;
ALTER TABLE public.strategic_notes      ADD COLUMN IF NOT EXISTS version integer NOT NULL DEFAULT 1;
ALTER TABLE public.candidate_positions  ADD COLUMN IF NOT EXISTS version integer NOT NULL DEFAULT 1;
ALTER TABLE public.ideas                ADD COLUMN IF NOT EXISTS version integer NOT NULL DEFAULT 1;
ALTER TABLE public.contacts             ADD COLUMN IF NOT EXISTS version integer NOT NULL DEFAULT 1;
ALTER TABLE public.tasks                ADD COLUMN IF NOT EXISTS version integer NOT NULL DEFAULT 1;
ALTER TABLE public.lessons              ADD COLUMN IF NOT EXISTS version integer NOT NULL DEFAULT 1;
ALTER TABLE public.lesson_patterns      ADD COLUMN IF NOT EXISTS version integer NOT NULL DEFAULT 1;
ALTER TABLE public.issues               ADD COLUMN IF NOT EXISTS version integer NOT NULL DEFAULT 1;

-- Deliberately NOT versioned, with reasons (so a future reader knows it was a
-- decision, not an omission):
--   * ticker_prices, ticker_fundamentals — machine-generated by Generate Data and
--     rewritten wholesale per (ticker, data_type); never hand-edited field-by-field.
--   * fund_nav_data — a derived daily series recomputed from the accounting ladder,
--     keyed by date; not a concurrently hand-edited document.
--   * interactions, contact_files — append-only logs (INSERT + DELETE, no UPDATE
--     path), so there is no update to lose.
--   * macro_regime_runs / _results / _signal — background pipeline output, not user
--     documents (retention-pruned, not edited).
--   * task_comments — exists but is unused by the app.
-- If any of these ever gains an in-place edit UI, add the column here and it will
-- pick up the trigger automatically.

-- Re-run the generic attach loop (same block as 030): attach bump_version to every
-- public BASE TABLE that now has a `version` column and lacks the trigger.
DO $$
DECLARE
  r record;
BEGIN
  FOR r IN
    SELECT c.table_name
    FROM information_schema.columns c
    JOIN information_schema.tables t
      ON t.table_schema = c.table_schema AND t.table_name = c.table_name
    WHERE c.table_schema = 'public'
      AND c.column_name = 'version'
      AND t.table_type = 'BASE TABLE'
  LOOP
    IF NOT EXISTS (
      SELECT 1 FROM pg_trigger
      WHERE tgname = 'bump_version_' || r.table_name
        AND tgrelid = format('public.%I', r.table_name)::regclass
    ) THEN
      EXECUTE format(
        'CREATE TRIGGER %I BEFORE UPDATE ON public.%I
           FOR EACH ROW EXECUTE FUNCTION public.bump_version();',
        'bump_version_' || r.table_name, r.table_name
      );
    END IF;
  END LOOP;
END $$;

-- ---------- Verify ----------
--   SELECT event_object_table FROM information_schema.triggers
--   WHERE trigger_name LIKE 'bump_version_%' ORDER BY 1;
--   -- expect: candidate_positions, contacts, documents, holdings, ideas, issues,
--   --         lessons, lesson_patterns, research_links, strategic_notes, tasks,
--   --         theses, valuation_models, watchlists, app_settings
